### ISSUE TITLE
qt 5.15: TypeError: Can't call meta function because I have no idea how to handle QSocketDescriptor

### ISSUE THREAD

**Issue by C0rn3j** [Syncplay/syncplay#321] opened 2020-06-04 16:43 UTC
Can't connect to any server on syncplay-git since I updated my system - I suspect it was Qt 5.15 that broke things.

Using latest git version:
```
syncplay-git 1.6.5.Beta1.r2.gd4ac455-1
```

I get this error over and over, and this traceback when I CTRL+C'd
```
TypeError: Can't call meta function because I have no idea how to handle QSocketDescriptor
TypeError: Can't call meta function because I have no idea how to handle QSocketDescriptor
Exception in thread Thread-2:
Traceback (most recent call last):
  File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/usr/lib/syncplay/syncplay/players/python_mpv_jsonipc/python_mpv_jsonipc.py", line 163, in run
    current_data = self.socket.recv(1024)
ConnectionResetError: [Errno 104] Connection reset by peer
^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C[1]    8999 segmentation fault (core dumped)  syncplay
```

**Comment by daniel-123** [comment] 2020-06-04 17:37
The traceback is an independent problem. It seems to occur often, but not always if mpv connected Syncplay client gets a `SIGINT` (which is what happens when you press ctrl+c).

From my very quick and dirty test in docker image of Arch, at very least I cannot reproduce the issue with `--no-gui`. Which seems slightly odd as it would imply the issue is somewhere in the GUI code, which shouldn't have anything to do with any sockets? Could you try out `--no-gui`?

**Comment by daniel-123** [comment] 2020-06-04 17:39
Thinking about it a second I'll also try to summon @blaenk since AUR package is his creation and he might be able to provide some insight here.

**Comment by C0rn3j** [comment] 2020-06-04 17:51
I can confirm that --no-gui works.

**Comment by daniel-123** [comment] 2020-06-04 17:55
For now that could be used as workaround I guess.

**Comment by daniel-123** [comment] 2020-06-05 09:34
It seems like this is an upstream bug [PYSIDE-1317](https://bugreports.qt.io/browse/PYSIDE-1317?gerritReviewStatus=Open).

I'll try to keep it open for a while just so people are aware of source of the problem and possible workaround.

**Comment by woolwood** [comment] 2020-06-07 11:31
For the record, this happens with the AppImage as well. If it's a PySide bug, maybe link to a different PySide version in the AppImage for now?

**Comment by daniel-123** [comment] 2020-06-07 16:40
@woolwood Thanks for heads up. It should be fixed now.

**Comment by FichteFoll** [comment] 2020-06-18 22:08
I just checked the 5.15 release plan and the 5.15.1 bugfix release is scheduled for 5.15.1 August 2020. Since I don't really want to wait another 6-8 weeks, I just decided to build pyside from git and that makes the UI work again (should've done that 2 weeks ago).

However, there is still an exception on the console when I close mpv or syncplay (and sometimes the process doesn't terminate for quite a while).

```
~ ▶ syncplay
Attribute Qt::AA_EnableHighDpiScaling must be set before QCoreApplication is created.
Exception in thread Thread-2:
Traceback (most recent call last):
  File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/usr/lib/syncplay/syncplay/players/python_mpv_jsonipc/python_mpv_jsonipc.py", line 163, in run
    current_data = self.socket.recv(1024)
ConnectionResetError: [Errno 104] Connection reset by peer
Unhandled Error
Traceback (most recent call last):
  File "/usr/lib/syncplay/syncplay/clientManager.py", line 16, in run
    syncplayClient.start(config['host'], config['port'])
  File "/usr/lib/syncplay/syncplay/client.py", line 841, in start
    reactor.run()
  File "/usr/lib/syncplay/syncplay/vendor/qt5reactor.py", line 303, in run
    self._blockApp.exec_()
  File "/usr/lib/syncplay/syncplay/vendor/qt5reactor.py", line 187, in write
    log.callWithLogger(w, _write)
--- <exception caught here> ---
  File "/usr/lib/python3.8/site-packages/twisted/python/log.py", line 103, in callWithLogger
    return callWithContext({"system": lp}, func, *args, **kw)
  File "/usr/lib/python3.8/site-packages/twisted/python/log.py", line 86, in callWithContext
    return context.call({ILogContext: newCtx}, func, *args, **kw)
  File "/usr/lib/python3.8/site-packages/twisted/python/context.py", line 122, in callWithContext
    return self.currentContext().callWithContext(ctx, func, *args, **kw)
  File "/usr/lib/python3.8/site-packages/twisted/python/context.py", line 85, in callWithContext
    return func(*args,**kw)
  File "/usr/lib/syncplay/syncplay/vendor/qt5reactor.py", line 182, in _write
    self.reactor._disconnectSelectable(w, why, False)
  File "/usr/lib/python3.8/site-packages/twisted/internet/posixbase.py", line 255, in _disconnectSelectable
    selectable.connectionLost(f)
  File "/usr/lib/python3.8/site-packages/twisted/internet/tcp.py", line 519, in connectionLost
    self._commonConnection.connectionLost(self, reason)
  File "/usr/lib/python3.8/site-packages/twisted/internet/tcp.py", line 327, in connectionLost
    protocol.connectionLost(reason)
  File "/usr/lib/python3.8/site-packages/twisted/protocols/tls.py", line 403, in connectionLost
    ProtocolWrapper.connectionLost(self, reason)
  File "/usr/lib/python3.8/site-packages/twisted/protocols/policies.py", line 125, in connectionLost
    self.wrappedProtocol.connectionLost(reason)
  File "/usr/lib/python3.8/site-packages/twisted/internet/endpoints.py", line 146, in connectionLost
    return self._wrappedProtocol.connectionLost(reason)
  File "/usr/lib/python3.8/site-packages/twisted/application/internet.py", line 438, in connectionLost
    self._lostNotification(reason)
  File "/usr/lib/python3.8/site-packages/twisted/application/internet.py", line 640, in <lambda>
    lambda _: self._clientDisconnected())
  File "/usr/lib/python3.8/site-packages/automat/_methodical.py", line 244, in _clientDisconnected
    value = output(oself, *a, **k)
  File "/usr/lib/python3.8/site-packages/automat/_methodical.py", line 283, in __call__
    return self.method(oself, *args, **kwargs)
  File "/usr/lib/python3.8/site-packages/twisted/application/internet.py", line 766, in _wait
    self._doWait()
  File "/usr/lib/python3.8/site-packages/twisted/application/internet.py", line 777, in _doWait
    delay = self._timeoutForAttempt(self._failedAttempts)
  File "/usr/lib/syncplay/syncplay/client.py", line 818, in retry
    self.ui.showMessage(getMessage("reconnection-attempt-notification"))
  File "/usr/lib/syncplay/syncplay/client.py", line 1581, in showMessage
    self.showOSDMessage(message, duration=constants.OSD_DURATION, OSDType=OSDType, mood=mood)
  File "/usr/lib/syncplay/syncplay/client.py", line 1611, in showOSDMessage
    self._client._player.displayMessage(message, int(duration * 1000), OSDType, mood)
  File "/usr/lib/syncplay/syncplay/players/mpv.py", line 132, in displayMessage
    self._listener.mpvpipe.show_text(messageString, duration, constants.MPLAYER_OSD_LEVEL)
  File "/usr/lib/syncplay/syncplay/players/python_mpv_jsonipc/python_mpv_jsonipc.py", line 584, in wrapper
    return self.command(name, *args)
  File "/usr/lib/syncplay/syncplay/players/python_mpv_jsonipc/python_mpv_jsonipc.py", line 617, in command
    return self.mpv_inter.command(command, *args)
  File "/usr/lib/syncplay/syncplay/players/python_mpv_jsonipc/python_mpv_jsonipc.py", line 316, in command
    self.socket.send({"command":command_list, "request_id": command_id})
  File "/usr/lib/syncplay/syncplay/players/python_mpv_jsonipc/python_mpv_jsonipc.py", line 156, in send
    raise BrokenPipeError("socket is closed")
builtins.BrokenPipeError: socket is closed

QFileSystemWatcher::removePaths: list is empty
QFileSystemWatcher::removePaths: list is empty
```

**Comment by daniel-123** [comment] 2020-06-18 22:11
@FichteFoll that exception is a separate problem that I've created issue #322 for.

**Comment by foresto** [comment] 2020-06-22 20:20
A workaround for those who installed from pip, until pyside 5.15.1 is released:

    pip3 uninstall pyside2
    pip3 install pyside2==5.14.2.2

**Comment by Chainfire73** [comment] 2020-07-26 06:04
> A workaround for those who installed from pip, until pyside 5.15.1 is released:
> 
> ```
> pip3 uninstall pyside2
> pip3 install pyside2==5.14.2.2
> ```

This worked. Thanks!

**Closed** 2020-09-13 20:14 UTC
Labels: External bug
