### ISSUE TITLE
Closing player should not close the application, etc

### ISSUE THREAD

**Issue by mbalandis** [Syncplay/syncplay#617] opened 2023-06-29 22:02 UTC
When you join the room the player pops up on top of it and you by all means need to keep it open and move it out of the way or else the application will close. It is not just that, the app closes on almost every opportunity it gets, including on error, on losing connection, on server down, on closing player, etc.

My suggestion is at the very least add an option to minimize when pressing X of the Syncplay itself and not close Syncplay when pressing the player's X.  This is how most modern applications work nowadays. I keep accidentally closing the entire session before the next item in the playlist... Or have a warning message before doing this... Or both?!

Would be great if this is implemented in next update.

**Comment by Et0h** [comment] 2023-07-03 18:20
Hi, thanks for sharing your experience and perspectives.

Syncplay closing when you close Syncplay or when you close the media player is the intended behaviour. I am sorry to hear that it does not suit your usage practice, but that is how Syncplay has worked ever since Syncplay was first released more than a decade ago and this is the first time I can recall that someone has asked for it to be changed. At present there are no plans to change this behaviour.

Syncplay is not supposed to close on disconnect, and I have never seen this behaviour. If anyone else comes across this happening thenI would be interested in the details of what player, OS and Syncplay version, and so on.

**Comment by mbalandis** [comment] 2023-07-04 11:08
Thank you for response and explanation of you reasoning behind it.

Please take the following as an honest review whether it is subjective or objective. By all means it is not an attack on your work as it is a great project and I am happy I found it as it would have been the first thing I tried if I found it first.

I am not particularly too fussed about this. It is all good as a whole so I have no complaints in general I just thought to bring this up. The application itself like you said been like this for more an a decade and imho works like applications used to work during Windows XP times.  If the application does what it suppose to do and does it well enough it is great but as time goes on it needs to catch up or it will fall behind. So in my case a simple tick box to let you choose not to close app on pressing X of player would do massive improvement already. Don't see it too difficult to implement (could be a catch) but not sure.

In regards of disconnecting it is not closing when someone else is disconnecting or anything it is when I had tried to self-host a server I had lots of trouble figure out how to get TLS, domain and hide my IP as chat just prints it. I know there are servers available to use but I like to self-host. I did figure out but it took me quite a while. I am happy to make a quick guide as well if anyone wants to know what I did. Other than that I keep closing it by accident by clicking X on a player :D In many cases if not ALL, app could just close the lobby and go back to settings window instead of closing entire process on every chance it gets haha :DDD

It is important to note that I stumbled across SyncPlay by complete accident by googling SyncPlay after I tried to figure out why SyncPlay (same name btw) on Jellyfin is buggy sometimes which I am currently using as well. I would have used it prior Jellyfin if I found it first. 

As a whole me and 2 of my friends simply watch Anime together on a schedule and what we use to do is each type ready and one of us do 3 2 1 GO! and we all click play at the same time. This would make it easier but for a small group it adds not much value just fun to use. For huge group of watchers however it is a GAME CHANGER as it requires lots of upload bandwidth to serve on Jellyfin for example + no way to really chat there and hope everything is in sync. 

- Normal viewing: Your local files, manual coordination
- Jellyfin (as an example): Host streams to everyone, still some manual coordination because of bugs and buffering.
- SyncPlay: Local Files and automatic coordination. (pretty much ideal for small or large groups if all can be bothered to install it :) )

Again, this is just my honest review. Don't take it too seriously if you think I am totally wrong. Feel free to counter it. I have few more bugs / improvements to report which I will when I have time. :)

**Closed** 2023-07-04 14:51 UTC
