### ISSUE TITLE
The % symbol corrupts the filename field

### ISSUE THREAD

**Issue by Dude00** [Syncplay/syncplay#163] opened 2017-12-07 07:24 UTC
![](https://i.imgur.com/5ZDmJNG.png)
Should display as: South Park - S15E12 1%.mp4

**Comment by Et0h** [comment] 2017-12-08 22:53
Thanks for reporting this issue. I've tested and can replicate. I will need to do some sort of code to replace % with &percent; or similar (unless someone else gets to it first).

**Comment by Et0h** [comment] 2017-12-09 11:20
Were you using MPC-HC?

I've made an initial investigation, and my best guess is that it is a MPC-HC bug rather than a Syncplay bug but it might be in the interface between the two. Can you confirm @Uriziel or @daniel-123 ?

**Comment by Et0h** [comment] 2017-12-10 14:50
@v0lt - I see this issue occur when using Syncplay with MPC-BE as well. Can you confirm whether or not this is an issue with the MPC-BE API and its handling of %'s?

**Comment by alby128** [comment] 2017-12-10 14:58
On Windows 7 and MPC-HC 1.7.13 + Syncplay 1.5.0, the player crashes if I try to open a file with a '%' char in its name. Everything works fine with the same file and VLC 2.x on Windows 7 and macOS 10.12

**Comment by NinoM4ster** [comment] 2018-03-19 21:10
Confirmed on **Windows 10 x64** _(1709)_, with **MPC-HC 1.7.13** and **Syncplay 1.5.2**.
I tried playing a web .MKV file which contained "**[ ]**" on it's name and MPC-HC crashed/stopped working, but it can run the same file by itself just fine.

**Comment by Et0h** [comment] 2018-04-08 14:45
I have now reported the bug at both https://trac.mpc-hc.org/ticket/6416 and https://sourceforge.net/p/mpcbe/tickets/300/

**Comment by albertosottile** [comment] 2018-04-26 14:25
@Et0h since this has been proved to be a bug in MPC, should we close this?

**Comment by Et0h** [comment] 2018-04-26 18:00
It is said to be fixed in MPC-BE r3521. Closing.

**Closed by Et0h** 2018-04-26 18:00 UTC
Labels: bug
