### ISSUE TITLE
Manjaro: 1.6.9 AppImage closes on joining room / launching vlc

### ISSUE THREAD

**Issue by SagittaryX** [Syncplay/syncplay#486] opened 2021-11-17 20:39 UTC
**Describe the bug**
When running the latest Manjaro GNOME and using the AppImage (through the AppImageLauncher tool) to run the program Syncplay will exit when hitting run after the configurations screen. The main program and the associated VLC instance will show up briefly before the program automatically stops running / exits with no error message.

**To Reproduce**
1. Run the latest version of Manjaro with GNOME as DE
2. Install appimagelauncher from the official Manjaro repository
3. Download Syncplay 1.6.9 AppImage and run it with the appimagelauncher
4. Select server / name / roomname
5. Hit store configuration and launch Syncplay
6. Program exits after briefly showing room and VLC instance

**Expected behavior**
Program should not exit after running / joining a lobby.

**Screenshots**

N/A

**Version and platform:**
 - OS: Manjaro (5.13.19-2-MANJARO) with GNOME 40.5
 - Syncplay 1.6.9 AppImage

**Additional context**
I recently switched from using Manjaro with KDE Plasma as my DE, on this version 1.6.9 did work fine. With GNOME however the program fails as described above. The 1.6.8 version of Syncplay however does work as described.

I am a relative Linux beginner, let me if there is anything I can do to provide more info / debugging.

**Comment by Et0h** [comment] 2021-11-18 14:53
Linux isn't my speciality, but here are some questions which will hopefully help us better understand the issue:
1. What version of VLC are you using?
2. Does it work if you use mpv rather than VLC?
3. Are you running Syncplay as a regular user or as an administrator/superuser?

My understanding is that @sxiii has been able to run Syncplay with Manjaro without issue, but not sure on versions/GNOME.

**Comment by daniel-123** [comment] 2021-11-18 16:07
As additional questions for quick diagnosis:

- Does the appimage produce any notable output when you run it from terminal?
- Are you running in Wayland or X session?

**Comment by SagittaryX** [comment] 2021-11-18 18:07
> What version of VLC are you using?

3.0.16 Vetinari

> Does it work if you use mpv rather than VLC?

It will not immediately exit as with VLC, though sound seems to be not working. Further elaborated below. Though I should not that if I integrate and run with the AppImageLauncher it seems to work as intended.

> Are you running Syncplay as a regular user or as an administrator/superuser?

> Does the appimage produce any notable output when you run it from terminal?

Not sure if I did exactly what you intended, I know there should ways to do this without AppImageLauncher but running the file from terminal using ./file and sudo ./file on my system is still launching the programs with the AppImageLauncher. Let me know if you want me to remove it and launch it some other way.

Running the AppImage from terminal with just ./file leads to the error. The only terminal output is "Attribute Qt::AA_EnableHighDpiScaling must be set before QCoreApplication is created.". Running the AppImage with sudo ./file does appear to work, but VLC spits out audio errors when trying to play a file: 

"Audio output failed:
The audio device "default" could not be used:
No such file or directory."

This is the whole terminal output for running the program as sudo (all before trying to run a file):

QStandardPaths: XDG_RUNTIME_DIR not set, defaulting to '/tmp/runtime-root'
Failed to connect to bus: $DBUS_SESSION_BUS_ADDRESS and $XDG_RUNTIME_DIR not defined (consider using --machine=<user>@.host --user to connect to bus of other user)
Failed to connect to bus: $DBUS_SESSION_BUS_ADDRESS and $XDG_RUNTIME_DIR not defined (consider using --machine=<user>@.host --user to connect to bus of other user)
QStandardPaths: XDG_RUNTIME_DIR not set, defaulting to '/tmp/runtime-root'
Attribute Qt::AA_EnableHighDpiScaling must be set before QCoreApplication is created.

I also tried using mpv while running as sudo ./file which resulted in no sound. Below is the extra terminal output when doing this, otherwise same as the above. Though as mentioned above, if AppImageLauncher has integrated the AppImage then it does work.

error: XDG_RUNTIME_DIR not set in the environment.
ALSA lib pcm_dmix.c:1035:(snd_pcm_dmix_open) unable to open slave
Cannot connect to server socket err = No such file or directory
Cannot connect to server request channel
jack server is not running or cannot be started
JackShmReadWritePtr::~JackShmReadWritePtr - Init not done for -1, skipping unlock
JackShmReadWritePtr::~JackShmReadWritePtr - Init not done for -1, skipping unlock

> Are you running in Wayland or X session?

Using X.

**Comment by daniel-123** [comment] 2021-11-18 19:07
I think I'd want first to establish a simplest scenario and see what happens. Because I'm not sure what AppImageLauncher actually does, I'd like to ask you to do the following:

1. Download the Syncplay AppImage directly from releases page here: https://github.com/Syncplay/syncplay/releases/tag/v1.6.9
2. Grant it permission to run either through gui or by running `chmod u+x Syncplay-1.6.9-x86_64.AppImage`
3. Run it with `./Syncplay-1.6.9-x86_64.AppImage`
4. Select mpv as video player, but don't set any video file in settings.
5. Click run syncplay.
6. What happened now? Do both Syncplay client window and media player window appear? Does the notification pane in Syncplay show information about successful connection to a server?
7. Open a media file, either from File -> Open in Syncplay or by drag-and-dropping it into mpv window.
8. Does the media file show up in player?
9. Unpause and see if video works.

If the problem is *just* about missing sound then it has nothing to do with Syncplay itself.

**Comment by daniel-123** [comment] 2021-11-18 19:52
I've done some testing myself in fresh Manjaro installation and I think I managed to significantly narrow down the problem:

- Syncplay works perfectly fine with mpv. This is also a workaround you can use for now.
- VLC on its own works normally
- Syncplay with VLC specifically causes VLC to crash/close very quickly after its started by Syncplay. Which seems that the problem is probably somewhere around our lua interface to it. What do you think @Et0h ?

**Comment by SagittaryX** [comment] 2021-11-18 20:21
My workaround for now is to use 1.6.8, mentioned in my additional notes as well but that version does not seem to have the issue.

**Comment by daniel-123** [comment] 2021-11-18 20:47
Hmm, 1.6.8 indeed works without problems. This is really quite weird as there wasn't any change that could obviously affect this. Only thing with least remote possibility of being related that changed between 1.6.8 and 1.6.9 is that AppImage now has bundled libxcb and libglib2 as result of those three commits: [1](https://github.com/Syncplay/syncplay/commit/184b8d9e478912a0bda0f0531be453c72f4daa4a#diff-53e2a72108bae586745e836fdd45b517a7d52871b5b40f76fbe20c3f5580ea46), [2](https://github.com/Syncplay/syncplay/commit/f558337b4c78ca985e33091d3e3354c2877cab14) and [3](https://github.com/Syncplay/syncplay/commit/868c26383f2206e19e2588b88e3aa13e440de6bc#diff-53e2a72108bae586745e836fdd45b517a7d52871b5b40f76fbe20c3f5580ea46). That and how the very process of building the AppImage always runs the latest version of its toolchain.

I guess we will have to investigate more. The problem also seems to persist in latest builds from main branch.

**Comment by vgambier** [comment] 2021-12-05 12:04
I am using Pop!_OS (with the GNOME desktop) and I encountered the same issue. I worked around it by switching to mpv (which is what I wanted to do anyway). I tried the AppImage, the .deb install, and the tarball install, and it was the same. Running it from the terminal without sudo also displayed "Attribute Qt::AA_EnableHighDpiScaling must be set before QCoreApplication is created".

The symptoms were a little different than what SagittaryX reported though, upon joining a server Syncplay simply became unresponsive, I could not interact with the UI at all. If I tried moving and resizing the window I would occasionally get glitchy results (like a "full-screen" window not actually being full screen, with parts of the UI hidden behind the borders of the monitor). Eventually once I spammed the close button my desktop would tell me the program is unresponsive, asking if I want to kill it.

**Comment by piorrro33** [comment] 2022-01-06 19:33
Can confirm the issue. I believe a better workaround would be to simply use the AUR version, rather than downgrading to 1.6.8.

**Comment by Et0h** [comment] 2023-11-09 19:28
I am closing this issue because Syncplay has now discontinued AppImage support. See: https://github.com/Syncplay/syncplay/issues/643 for more details. If an issue recurs with the Deb package or Tarball then please re-open this comment and let us know of the details.

**Closed by Et0h** 2023-11-09 19:28 UTC
Labels: bug / problem, Linux/AppImage
