### ISSUE TITLE
Syncplay rewinds playing media when media directory content changes

### ISSUE THREAD

**Issue by rechbergerd** [Syncplay/syncplay#330] opened 2020-06-24 18:35 UTC
Hi!
I have repeatedly observed, that with version 1.6.5 (dev), when a file operation is ongoing while playing back media, the playback suddenly rewinds to 0:00 and so restarts.

Scenario:
- managed room
- one room operator
- adding or removing a file in the designated media folder hierachy
- presently only one media folder listed
- Windows 7

Kindest regards, and keep the best work!

**Comment by daniel-123** [comment] 2020-06-25 06:53
I haven't seen this problem occur on Linux, so it's likely at very least OS dependent.

Is your media folder on local HDD, SSD, network share or something else? What order of magnitude is the number of files in it (thousands or hundreds of thousands or millions?) We've had some performance issues with very large numbers of files in scanned folders on slow devices in the past.

Could you test with a bit older version of Syncplay? Between 1.6.4 and 1.6.5 there was some work around the code for managing details of behavior when switching files and such as mentioned in #315

**Comment by rechbergerd** [comment] 2020-06-25 15:02
- Type of media: local HDD, magnetic, no SSD
- Number of files: not more than 75
- Number of folders: not more than 10 folders
- Size of media directory: not more than 130 GB

Question: for the managed room, does only me (the room operator) switch between the versions, or all the members of the room?

**Comment by Et0h** [comment] 2020-06-25 15:29
Just tried to reproduce on Windows 10 and the issue did not occur. My best guess is that you are not using playlists correctly, and are trying to change the file by loading it into your media player rather than by adding it to the playlist.

Rather than manually loading a file into a media player, you are supposed to add the file to the playlist and then when you change file you change your selection of the playlist. Others with that file in their playlist should then automatically load the right file. When you change playlist selection the playback is supposed to reset to 0.

**Comment by rechbergerd** [comment] 2020-06-25 17:03
I am aware how it is supposed to be working
- Player linked: MPC-HC x64 (K-Lite Codec Pack)

Additional details:
- The media directory doubles as a place sychroniced with a NextCloud server
- When a file event happends (added, deleted), the Syncplay resets my "Ready-State" with ready, regardless of earlier selection
- I can not move the "pointer" of the active item in the playlist, as suggested by @Et0h  ... it sticks to one file, until it gets removed from the shared playlist, then it moves to the next underneath, if none there, it moves to the next above ...

**Comment by Et0h** [comment] 2020-06-25 17:23
@rechbergerd Does the issue occur if you use mpv or VLC?

**Comment by rechbergerd** [comment] 2020-06-25 20:23
test with MPV (x86_64, Version 20200510, git 4e94b21):
- jumps from (e.g.) 4:12 to 0:00
- next second: jumps from 0:00 to 4:13

**Comment by rechbergerd** [comment] 2020-06-25 20:28
test with VLC (win32, 3.0.11, as 7z archive portable)
- jumps to 0:00 once file event recognised

**Comment by daniel-123** [comment] 2020-06-29 12:32
Hmm, could you temporarily set media directories to a plain, non-synced folder?

My gut tells me that there might be some weird interaction between Syncplay and NextCloud client. That said I tested it with NFS file share on Linux and that worked without issues.

**Comment by rechbergerd** [comment] 2020-07-01 13:27
I did copy the directory, selected a media that has been copied in full (while doing the remaining copying) and played it. No joy, after a minute or so, when a new file gets created (from copying), the playback stops, rewinds to 0:00, and starts. Filesystem is again NTFS, with no sync of nextcloud on this directory.

**Comment by Et0h** [comment] 2021-03-04 19:03
I'm closing this issue for now because I've not heard any other reports of this issue and haven't been able to reproduce it on Windows 10. Windows 7 reached EOL on the 14th of January 2020 and so in line with Syncplay policy we no longer officially support it. If someone comes across this issue on a supported operating system then please post detailed instructions on how to reproduce.

**Closed by Et0h** 2021-03-04 19:03 UTC
Labels: bug / problem
