### ISSUE TITLE
Syncplay does not connect to server

### ISSUE THREAD

**Issue by Techhead0** [Syncplay/syncplay#341] opened 2020-07-27 17:13 UTC
Running Syncplay 1.6.5 on Manjaro Linux, attempts to connect to `syncplay.pl` server universally return "Connection with server failed". Noticed on multiple days, and using various default ports.

Issue first seen on July 12, 2020 after approximately a month of non-use.
Upgraded from 1.6.4a-2 to 1.6.5-1 on July 11 via Package Manager.

**Comment by benferreri** [comment] 2020-07-27 19:00
I experienced the same issue this weekend, using Arch Linux, trying to connect to `syncplay.pl` server with syncplay version 1.6.5. I tried multiple different available ports, and the issue persisted.

**Comment by Et0h** [comment] 2020-08-06 11:46
I use Windows so can only be of limited support. It could potentially be a firewall or permission issue. You could try using a different release of Syncplay, e.g. using the

**Comment by Techhead0** [comment] 2020-08-12 07:18
Took the time to look through firewall settings, relevant ports are not blocked. Attempts at using an earlier release have not successfully installed, to my consternation

**Comment by Et0h** [comment] 2020-08-12 08:10
It works fine for me on Windows so if none of the Linux versions work then maybe you could try running it through Wine or similar

**Comment by Ericchi** [comment] 2020-09-12 20:02
I have the same exact issue and `--no-gui` worked for me, but this isn't clearly a solution, since I can't use the GUI.

**Comment by Et0h** [comment] 2020-09-12 20:33
@Ericchi Have you tried the work around mentioned in #321?

**Comment by daniel-123** [comment] 2020-09-13 18:25
Expanding on what @Et0h mentioned: specifically in development version 5.15 of PySide2 there is a bug preventing Syncplay from working with GUI. Is that the version where you see the issues @Ericchi @rijenkii ?

If that's the case only real solution is to either upgrade PySide2 to first release (5.15.1) or downgrade it to 5.14.X. Alternatively current AppImage version on bintray should have latest PySide2 included.

**Comment by benferreri** [comment] 2020-09-13 18:29
I can confirm that I was able to fix the issue by downgrading PySide2 to 5.14.2 on Arch Linux.

**Comment by daniel-123** [comment] 2020-09-13 18:34
@benferreri Is it possible for you to test with PySide2 5.15.1 on Arch? It seems that it has been updated very recently from 5.15 according to this link: https://www.archlinux.org/packages/extra/x86_64/pyside2/.

If it's confirmed to work, then hopefully this issue would be on straight way to being closed as effectively a duplicate of #321 that's solved now.

**Comment by benferreri** [comment] 2020-09-13 18:40
just updated, and it does indeed work with PySide2 5.15.1 on Arch Linux (which is latest version in Arch repos)

**Closed** 2020-09-13 20:14 UTC
Labels: Linux
