### ISSUE TITLE
Project IINA Support

### ISSUE THREAD

**Issue by jeep70** [Syncplay/syncplay#144] opened 2017-09-12 19:39 UTC
I'm seeing Mac development on the horizon, and this is my favorite player for Mac. I figured since it was MPV based, it would be easy to support.
https://lhc70000.github.io/iina/

**Comment by alby128** [comment] 2017-09-14 13:14
Just a preliminary question, do you know if it is possible to control IINA via terminal, as for mpv? I installed it on my system via cask, but did not find any CLI for it.

**Comment by jeep70** [comment] 2017-09-14 13:24
I'm not actually sure, but I found some relevant issues that might help answer your question.
https://github.com/lhc70000/iina/issues/875
https://github.com/lhc70000/iina/issues/58

**Comment by alby128** [comment] 2017-09-14 13:30
Yep, according to the roadmap it has to be implemented yet. I am afraid that until they do that, we have no way to interact with IINA and add support for Syncplay. I guess we just have to wait and then try to adjust our mpv module accordingly.

**Comment by jeep70** [comment] 2017-09-14 13:31
I don't suppose any of these pages would be useful?
https://github.com/lhc70000/iina/wiki/MPV-Options-and-Properties
https://github.com/lhc70000/iina/wiki/Use-youtube-dl-with-IINA
https://github.com/lhc70000/iina/wiki/Use-SVP-with-IINA

**Comment by alby128** [comment] 2017-09-14 13:32
I already read those, as far as I understood there is no way to control the player status after IINA is launched from the command line...

**Comment by jeep70** [comment] 2017-09-14 13:34
Okay, thanks for your time.

**Comment by alby128** [comment] 2017-09-14 13:37
Thank you, maybe you could comment again when they release a functional CLI for IINA.

**Comment by Et0h** [comment] 2017-09-14 17:26
If it doesn't support terminal (which is what Syncplay currently uses for mpv) does it at least support the mpv JSON IPC protocol ?

**Comment by alby128** [comment] 2017-09-14 17:39
From here: https://github.com/lhc70000/iina/wiki/Use-SVP-with-IINA it seems that it does, by adding an option in IINA's preferences. I just tried it and obtained a reasonable answer:
`Albertos-iMac:~ alberto$ echo '{ "command": ["get_property", "playback-time"] }' | socat - /tmp/mpvsocket
{"data":499.749000,"error":"success"}`

**Comment by Et0h** [comment] 2017-09-16 22:22
I don't use OSX so it'd definitely need someone to take it up not just to port it over but also to maintain it.

**Comment by jeep70** [comment] 2017-11-09 15:31
Coming soon
https://github.com/lhc70000/iina/pull/1181

**Comment by alby128** [comment] 2017-11-09 15:34
Great, let's wait for a release. In the meantime, @etoh do we use any `--no-*` option in mpv.py?

**Comment by Et0h** [comment] 2017-11-12 12:28
@jeep70 Great news! 👍 

@alby128 We use "no-osd set" to set properties without affecting the OSD, but we don't make use of any  command line options which start with --no. Depending on your definition, you could say --input-terminal=no is equivalent to --no-input-terminal, but if the issue is using the --no prefix style to set variables then that doesn't happen (unless someone manually sets up a --no command in Syncplay player arguments).

On Windows, the default command line options are: `['--force-window', '--idle', '--hr-seek=always', '--keep-open', '--msg-level=all=error,cplayer=info,term-msg=info', '--input-terminal=no', '--input-file=/dev/stdin', '--term-playing-msg=<SyncplayUpdateFile>\nANS_filename=${filename}\nANS_length=${=length:${=duration:0}}\nANS_path=${path}\n</SyncplayUpdateFile>', '--terminal=yes'] `

**Comment by Et0h** [comment] 2017-12-08 22:18
https://github.com/lhc70000/iina/pull/1181 seems to have been merged into the develop branch. Is the IINA develop branch working properly with Syncplay @jeep70 (assuming you change the mpv code to detect IINA as mpv)?

**Comment by Et0h** [comment] 2017-12-10 16:14
To add support is something like: (1) Create icon and list it in Py2exe, (2) Create new .py which is a subclass of NewMpvPlayer, (3) reference the player in other Syncplay code so it shows up. See https://github.com/Syncplay/syncplay/commit/88113d8e1587edf8316c90884e2b84ea0217a9df and https://github.com/Syncplay/syncplay/commit/117a45b7cbec34c6ba3c0c8407166e18994269da for examples of this being done for MPC-BE.

However, adding support also means testing it and then maintaining compatibility in future versions of the player so I suggest only a dev who regularly uses IINA and is willing to be the long-term IINA lead works on adding initial IINA support to Syncplay.

**Comment by jeep70** [comment] 2017-12-10 17:41
I can't seem to get syncplay to work from the git - I'm using python2 to open the client and it crashes with `global name GraphicalUI is not defined` after pressing run syncplay (unmodified code and using stock mpv). I also tried building it with py2app but that just crashes the same way

**Comment by alby128** [comment] 2017-12-10 18:47
There is something wrong either in the version you downloaded or in your python environment. Please check if you have twisted, appnope, and pyobjc installed. If you are not sure, just run `pip2 install twisted appnope pyobjc`.

**Comment by jeep70** [comment] 2017-12-10 19:27
That worked, but using IINA doesn't work with syncplay it seems. I changed the code a little so that every path was accepted for mpv, but it just becomes completely unresponsive after going to the server window. Selecting a file in IINA doesn't do anything. Quitting IINA results in this dialog box
![screen shot 2017-12-10 at 2 24 27 pm](https://user-images.githubusercontent.com/10716694/33808517-d9d79ff0-ddb5-11e7-88d2-c85a0c3ada37.png)
This is with the built develop branch of IINA. Terminal Log:
```Benjamins-iMac:syncplay benjamin$ python2 syncplayClient.py
2017-12-10 14:19:41.057 Python[8544:967879] +[NSSegmentedCell(StaticMethods) _image_state_for_visual_state:style:trackingMode:]: Unknown NSSegmentVisualState 0
2017-12-10 14:19:41.057 Python[8544:967879] +[NSSegmentedCell(StaticMethods) _image_state_for_visual_state:style:trackingMode:]: Unknown NSSegmentVisualState 0
2017-12-10 14:19:42.586 Python[8544:967879] +[NSSegmentedCell(StaticMethods) _image_state_for_visual_state:style:trackingMode:]: Unknown NSSegmentVisualState 0
2017-12-10 14:19:42.586 Python[8544:967879] +[NSSegmentedCell(StaticMethods) _image_state_for_visual_state:style:trackingMode:]: Unknown NSSegmentVisualState 0
2017-12-10 14:19:43.465 Python[8544:967879] +[NSSegmentedCell(StaticMethods) _image_state_for_visual_state:style:trackingMode:]: Unknown NSSegmentVisualState 0
2017-12-10 14:19:43.465 Python[8544:967879] +[NSSegmentedCell(StaticMethods) _image_state_for_visual_state:style:trackingMode:]: Unknown NSSegmentVisualState 0
2017-12-10 14:19:46.753 Python[8544:967879] +[NSSegmentedCell(StaticMethods) _image_state_for_visual_state:style:trackingMode:]: Unknown NSSegmentVisualState 0
2017-12-10 14:19:46.753 Python[8544:967879] +[NSSegmentedCell(StaticMethods) _image_state_for_visual_state:style:trackingMode:]: Unknown NSSegmentVisualState 0
2017-12-10 14:19:48.020 Python[8544:967879] +[NSSegmentedCell(StaticMethods) _image_state_for_visual_state:style:trackingMode:]: Unknown NSSegmentVisualState 0
2017-12-10 14:19:48.020 Python[8544:967879] +[NSSegmentedCell(StaticMethods) _image_state_for_visual_state:style:trackingMode:]: Unknown NSSegmentVisualState 0
2017-12-10 14:19:50.615 Python[8544:967879] +[NSSegmentedCell(StaticMethods) _image_state_for_visual_state:style:trackingMode:]: Unknown NSSegmentVisualState 0
2017-12-10 14:19:50.615 Python[8544:967879] +[NSSegmentedCell(StaticMethods) _image_state_for_visual_state:style:trackingMode:]: Unknown NSSegmentVisualState 0
2017-12-10 14:19:52.003 Python[8544:967879] +[NSSegmentedCell(StaticMethods) _image_state_for_visual_state:style:trackingMode:]: Unknown NSSegmentVisualState 0
2017-12-10 14:19:52.003 Python[8544:967879] +[NSSegmentedCell(StaticMethods) _image_state_for_visual_state:style:trackingMode:]: Unknown NSSegmentVisualState 0
2017-12-10 14:19:55.371 Python[8544:967879] +[NSSegmentedCell(StaticMethods) _image_state_for_visual_state:style:trackingMode:]: Unknown NSSegmentVisualState 0
2017-12-10 14:19:55.371 Python[8544:967879] +[NSSegmentedCell(StaticMethods) _image_state_for_visual_state:style:trackingMode:]: Unknown NSSegmentVisualState 0
2017-12-10 14:19:58.171 Python[8544:967879] +[NSSegmentedCell(StaticMethods) _image_state_for_visual_state:style:trackingMode:]: Unknown NSSegmentVisualState 0
2017-12-10 14:19:58.171 Python[8544:967879] +[NSSegmentedCell(StaticMethods) _image_state_for_visual_state:style:trackingMode:]: Unknown NSSegmentVisualState 0
objc[8544]: Class FIFinderSyncExtensionHost is implemented in both /System/Library/PrivateFrameworks/FinderKit.framework/Versions/A/FinderKit (0x7fff97964a70) and /System/Library/PrivateFrameworks/FileProvider.framework/OverrideBundles/FinderSyncCollaborationFileProviderOverride.bundle/Contents/MacOS/FinderSyncCollaborationFileProviderOverride (0x1264cacd8). One of the two will be used. Which one is undefined.
2017-12-10 14:22:05.406 Python[8544:967879] modalSession has been exited prematurely - check for a reentrant call to endModalSession:
2017-12-10 14:23:57.162 IINA[8570:986310] MPV log: [vd] warn: Falling back to software decoding.```

**Comment by Et0h** [comment] 2017-12-10 21:11
@jeep70 If you run Syncplay in --debug mode is there anything interesting in the Syncplay<->IINA communication? Have you tried Syncplay in both NewMpvPlayer and OldMpvPlayer modes by changing the run static method in MpvPlayer (mpv.py)?

**Comment by jeep70** [comment] 2017-12-10 21:46
Just running it in debug mode didn't seem to do anything different, but when i switched the mode check in the run method, I got a different result.

```Benjamins-iMac:syncplay benjamin$ python2 syncplayClient.py --debug
objc[10842]: Class FIFinderSyncExtensionHost is implemented in both /System/Library/PrivateFrameworks/FinderKit.framework/Versions/A/FinderKit (0x7fff97964a70) and /System/Library/PrivateFrameworks/FileProvider.framework/OverrideBundles/FinderSyncCollaborationFileProviderOverride.bundle/Contents/MacOS/FinderSyncCollaborationFileProviderOverride (0x10c80ccd8). One of the two will be used. Which one is undefined.
Benjamins-iMac:syncplay benjamin$ python2 syncplayClient.py --debug
objc[10859]: Class FIFinderSyncExtensionHost is implemented in both /System/Library/PrivateFrameworks/FinderKit.framework/Versions/A/FinderKit (0x7fff97964a70) and /System/Library/PrivateFrameworks/FileProvider.framework/OverrideBundles/FinderSyncCollaborationFileProviderOverride.bundle/Contents/MacOS/FinderSyncCollaborationFileProviderOverride (0x129020cd8). One of the two will be used. Which one is undefined.
2017-12-10 16:41:25.486 Python[10859:1460032] modalSession has been exited prematurely - check for a reentrant call to endModalSession:
[16:41:25] Not playing current index - Index none or length issue
[16:41:48] player >> cycle pause
[16:41:48] <mpv> Throttling message send, so sleeping for 0.05
[16:41:48] player >> get_property filename
[16:41:48] <mpv> Throttling message send, so sleeping for 0.05
[16:41:48] player >> get_property length
[16:41:48] <mpv> Throttling message send, so sleeping for 0.05
[16:41:48] player >> get_property path
[16:41:57] player << IINA 0.0.15 Build 56
[16:41:57] player << This binary is not intended for being used as a command line tool. Please use the bundled iina-cli.
[16:41:57] player << Please ignore this message if you are running in a debug environment.
[16:41:57] player >> quit
[16:41:57] Cannot switch to None index in playlist```

Everything after modalSession has been exited prematurely showed up after i force quitted IINA. Pretty much everything else is the same. This is what happens when I try using [iina-cli](https://i.imgur.com/rD0Bioo.png)
```Benjamins-iMac:syncplay benjamin$ python2 syncplayClient.py --debug
objc[10881]: Class FIFinderSyncExtensionHost is implemented in both /System/Library/PrivateFrameworks/FinderKit.framework/Versions/A/FinderKit (0x7fff97964a70) and /System/Library/PrivateFrameworks/FileProvider.framework/OverrideBundles/FinderSyncCollaborationFileProviderOverride.bundle/Contents/MacOS/FinderSyncCollaborationFileProviderOverride (0x12cf19cd8). One of the two will be used. Which one is undefined.
2017-12-10 16:44:32.125 Python[10881:1464821] modalSession has been exited prematurely - check for a reentrant call to endModalSession:
[16:44:32] Not playing current index - Index none or length issue
[16:44:32] player >> cycle pause
[16:44:32] <mpv> Throttling message send, so sleeping for 0.05
[16:44:32] player << Cannot find IINA binary. This command line tool only works in IINA.app bundle.
[16:44:32] player >> get_property filename
[16:44:32] <mpv> Throttling message send, so sleeping for 0.05
[16:44:32] <mpv> Throttling message send, so sleeping for 0.05
[16:44:32] player >> quit
[16:44:32] <mpv> Throttling message send, so sleeping for 0.05
[16:44:32] player >> get_property length
[16:44:32] <mpv> Throttling message send, so sleeping for 0.05
[16:44:32] player >> get_property path
[16:44:32] Cannot switch to None index in playlist
[16:44:32] client/server >> {"Hello": {"username": "\u0280\u1d0f\u0274 \u1d0a\u1d0f\u029c\u0274s\u1d0f\u0274", "version": "1.2.255", "room": {"name": "Madagaskar98k"}, "realversion": "1.5.0"}}
[16:44:32] player >> show_text "Connection with server lost, attempting to reconnect" 3000 1
Benjamins-iMac:syncplay benjamin$ ```

I can't seem to open up the app bundle in syncplay. It should be noted that all of the above shows up immediately and i do not have to do anything to IINA for that to happen.

**Comment by Et0h** [comment] 2017-12-10 21:52
@jeep70 Are you running IINA with the --stdin command line argument?

**Comment by Et0h** [comment] 2017-12-14 18:18
Sorry I can't be of any more assistance in figuring this out. Maybe you could try and get an IINA dev to join the effort.

**Comment by Et0h** [comment] 2018-04-26 20:06
Syncplay already supports mpv and VLC. If IINA ever adds support for Syncplay then please update this issue, but until then I'm happy to consider this matter on pause.

**Closed by Et0h** 2018-04-26 20:06 UTC
Labels: enhancement

**Comment by jeep70** [comment] 2018-04-26 20:29
That's reasonable. Thank you for entertaining the idea.

**Comment by albertosottile** [comment] 2020-12-06 21:36
Syncplay 1.6.7 will add support for IINA. The first beta of this release is avaliable here: https://github.com/Syncplay/syncplay/releases/tag/v1.6.7-Beta1. Any feedback would be truly appreciated!

**Comment by jurplel** [comment] 2020-12-08 01:28
Awesome!
