### ISSUE TITLE
Appimage not working in Debian 10 since 1.6.7

### ISSUE THREAD

**Issue by currificado** [Syncplay/syncplay#499] opened 2022-01-24 15:03 UTC
Syncplay version 1.6.6 works just fine, but starting from 1.6.7, I get:

```
qt.qpa.plugin:` Could not load the Qt platform plugin "xcb" in "" even though it was found.
This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.

Available platform plugins are: eglfs, linuxfb, minimal, minimalegl, offscreen, vnc, wayland-egl, wayland, wayland-xcomposite-egl, wayland-xcomposite-glx, webgl, xcb.
```

**Comment by daniel-123** [comment] 2022-01-25 12:04
This seems to be a duplicate of #380, which I think is fixed as of f558337 and release 1.6.9.

Do you still have this issue with 1.6.9?

**Comment by currificado** [comment] 2022-01-25 12:57
@daniel-123 Yes, I downloaded 1.6.9 first since it's the latest release. As I get this error, I decided to try the previous releases: 1.6.8, 1.6.7 and finally 1.6.6 which it works for me. Then I tested some `AppImage`'s previous than 1.6.6 and they also work fine. It seems that something changed starting from 1.6.7.

**Comment by daniel-123** [comment] 2022-01-25 13:18
I guess I'll test it again. I do remember testing the f558337 and it worked fine on my Debian 10 back then, but maybe something slipped through.

**Comment by daniel-123** [comment] 2022-12-07 17:53
@currificado can you try an AppImage built in newer environment? There is a few in result of [this action](https://github.com/Syncplay/syncplay/actions/runs/3641430192). I'm not sure if it will help with anything on older Debian, but maybe there is something worth looking at.

**Comment by Et0h** [comment] 2023-11-09 19:27
I am closing this issue because Syncplay has now discontinued AppImage support. See: https://github.com/Syncplay/syncplay/issues/643 for more details. If an issue recurs with the Deb package or Tarball then please re-open this comment and let us know of the details.

**Closed by Et0h** 2023-11-09 19:27 UTC
Labels: bug / problem, Linux/AppImage
