### ISSUE TITLE
On windows 10, syncplay crashes with 'syncplay stopped working' at pressing 'safe config and play'

### ISSUE THREAD

**Issue by mokrates** [Syncplay/syncplay#100] opened 2016-05-16 12:17 UTC

**Comment by Uriziel** [comment] 2016-06-12 11:32
works for me

**Comment by blaenk** [comment] 2016-06-12 17:28
I can confirm it works for me and my friends. What version of syncplay are
you using and what version of what player?

**Comment by Et0h** [comment] 2016-06-12 18:25
Also, are you using any security/anti-virus software which could be causing an issue such as Avast and its Sandbox feature? Does it crash if you are run Syncplay without storing config?

**Comment by Et0h** [comment] 2016-07-07 18:54
Is the issue resolved in Syncplay 1.4.0 RC1? http://syncplay.pl/syncplay-1-4-0/

**Comment by Et0h** [comment] 2016-07-17 12:40
If you were using VLC this might be due to running an older version. In 1.4.0 RC2 Syncplay should now tell you to run a new version rather than trying to run anyway and risking a crash.

**Closed** 2016-08-30 12:16 UTC
Labels: Requires User Input
