### ISSUE TITLE
Problems lauching syncplay (shiboken2)

### ISSUE THREAD

**Issue by kiev1120** [Syncplay/syncplay#436] opened 2021-07-13 16:57 UTC
PySide2/__init__.py: Unable to import shiboken2 from C:\Users\green\Desktop\Syncplay_1.6.8_Portable\lib/libsync.zip

it work worked just 2 days before but now i can't seem to launch it. anyone can help?

**Comment by xRUSSELL** [comment] 2021-07-16 10:43
Same Issue

**Comment by Harry466** [comment] 2021-07-21 15:19
Yeah! Me too having same problem. @Admin please see the screenshots that I have attached and please help me to solve this issue...
![Screenshot (237)](https://user-images.githubusercontent.com/87762746/126514110-593091a1-e000-4352-a0f1-e65f220b4cca.png)
![Screenshot (238)](https://user-images.githubusercontent.com/87762746/126514223-2fc0bbd9-47ae-4c5a-910b-2d24475ccf37.png)

**Comment by kittsville** [comment] 2021-07-21 15:51
Non-Syncplay users have had similar `Unable to import shiboken2` errors because they had a Python version greater than 3.6 installed:
https://github.com/alicevision/meshroom/issues/901#issuecomment-631914930

Looking in your Screenshot you might have Python 3.8 installed. I write Python apps, so have Python installed on my laptop.

Can @kiev1120 and @xRUSSELL confirm if they already have Python installed and if so, what version?

**Comment by kittsville** [comment] 2021-07-21 15:52
As a temporary fix I downgraded to Synplay 1.6.7, which worked without issue.

**Comment by albertosottile** [comment] 2021-07-21 16:10
I am afraid this is a duplicate of #425.

**Closed by albertosottile** 2021-07-21 16:10 UTC
Labels: Windows
