### ISSUE TITLE
Syncplay and VLC on Ubuntu causes syncplay.lua error

### ISSUE THREAD

**Issue by nlieb** [Syncplay/syncplay#301] opened 2020-04-20 01:06 UTC
Hello,

When starting synplay I get this error:

```
VLC has reported that the syncplay.lua interface script has not been installed. Please refer to https://syncplay.pl/LUA/ for instructions.
```

This seems to be an old issue but this is with syncplay 1.6.4 and VLC 3.0.8 (both installed via snap) on Ubuntu 18.04. Thank you

**Comment by Et0h** [comment] 2020-04-29 21:03
I've had others report issues with VLC and Syncplay on Ubuntu/Snap recently, so seems like something might have changed either with VLC or with Snap which is causing an issue. See also #302.

**Comment by bobismijnnaam** [comment] 2020-05-02 07:12
Hey everyone,

If I start VLC myself it seems it can find the file, as it is present in my extensions window. When I open the extensions window in VLC opened by syncplay, the extension is not there, so it seems something prevented it from loading.

Maybe the args that are specified by syncplay when vlc is started constrain it too much? I think that happens in the following file/line: https://github.com/Syncplay/syncplay/blob/a9172f9fa66a8eff488a76b209015411ef641ddb/syncplay/players/vlc.py#L411

Two humble ideas, as a complete outsider:

1. Maybe the module path arg in slave_args can be left out and vlc can figure it out on its own?  (I am probably misunderstanding how vlc.py works though...) 
2. The hardcoded path `/usr/lib/vlc/lua/intf/` does not exist on my pc (ubuntu 18.04). Instead, vlc is located at `/usr/lib/x86_64-linux-gnu/vlc/lua/`, which also contains an extension I installed. Should this path be included as well? Or, maybe syncplay can prefer to use the `vlcIntfUserPath`? Since the intf folder in my local extension dir does exist.

In any case, thanks for developing syncplay. Maybe in a few days I'll be able to help some more.

**Comment by Et0h** [comment] 2020-05-02 14:51
Can someone with the issue please try to remove the

**Comment by Et0h** [comment] 2020-05-02 14:53
In line with the suggestion from @bobismijnnaam I have now now deleted the line `playerController.SLAVE_ARGS.append('--data-path={}'.format(playerController.vlcDataPath))` from `VLC.py` which I think was redundant in any case. Can someone please try the GIT HEAD version of Syncplay and let me know if it fixes VLC on Ubuntu.

**Comment by bobismijnnaam** [comment] 2020-05-03 08:13
Works for me! Ubuntu 18.04, python 3.5, and installed the dependencies in the requirements.txt files.

**Comment by aboode95** [comment] 2020-05-04 17:04
I think there is a issue with Ubuntu 20.04 being a x64 system with no preinstalled 32bit libraries?

I had snap installed vlc. Then I tried syncplay as appimage. And then from snap-store. Both didn't work. And when I tried compiling syncplay from source, installing the requirement.txt, I couldn't install `pip3 install pypiwin32==223`. Went ahead and built syncplay anyway with python 2.7. Ran syncplay and it gave the same "syncplay.lua" error.

**Comment by aboode95** [comment] 2020-05-04 17:33
okay so I uninstalled the snap-vlc. And installed apt-vlc with `sudo apt install vlc`. Syncplay v1.6.5 is working with the apt-vlc (VLC v3.0.9.2)

**Comment by aboode95** [comment] 2020-05-04 18:10
Tested out again with Syncplay v1.6.5 and snap-vlc (VLC v3.0.10). It didn't work. same error "syncplay.lua"

**Comment by albertosottile** [comment] 2020-05-04 22:24
> I think there is a issue with Ubuntu 20.04 being a x64 system with no preinstalled 32bit libraries?

`snapd` should automatically install the `core` snap with these libraries.

> Ran syncplay and it gave the same "syncplay.lua" error.

Once again, I am unable to reproduce. Here there is what I did, step by step
- Start with a fresh Ubuntu 20.04 VM
- `sudo apt update`
- `sudo apt upgrade`
- `sudo snap install vlc`
- Open VLC for the first time from the Applications menu, then close it (this should not be necessary but, just in case...)
- `sudo snap install syncplay --classic`
- Open Syncplay from the Applications menu
- Confirm that Syncplay picks the right player path in the Config dialog (`/snap/bin/vlc`)
- Store configuration and run Syncplay
- Syncplay runs fine with VLC

Incidentally, I found out that the application icons are indeed broken in the 20.04 snap, we should investigate that -> @daniel-123 

@aboode95 Did you try Syncplay from snap? Could you try following these steps? Thanks for your help.

**Comment by aboode95** [comment] 2020-05-05 02:27
@albertosottile I am happy to help! And it's really nothing. Indeed I should be thanking you!

So, I decided to do a fresh install of Ubuntu 20.04 and then follow your steps. Unfortunately, it didn't work. I still got the `syncplay.lua` error. Both vlc and syncplay was installed using snap. And I did open vlc before installing syncplay. 

Though I should mention that I had a power outage in my area and my computer shut down when I was installing vlc. When electricity came back, I had to run `snap changes` and `sudo snap abort 3` because I was getting error `snap vlc has “install-snap” change in progress`. After aborting, I was able to install vlc and continue to follow your steps.

I should also mention that I have a `minimal installation` of Ubuntu 20.04. Could they be causing the issue?

**Comment by aboode95** [comment] 2020-05-05 10:36
I also tried with `syncplay from snap` with `apt-vlc` (`sudo apt install vlc`). It didn't work.
the versions were: Snap v1.6.4 and vlc v3.0.9.2

I then tried `vlc v3.0.9.2 (apt install)` with `syncplay-appimage` (synplay v.1.6.4a). This worked.

**Comment by albertosottile** [comment] 2020-05-05 16:36
@aboode95 
> I should also mention that I have a `minimal installation` of Ubuntu 20.04. Could they be causing the issue?

I ran exactly the same steps described before but on a "Minimal Installation" of Ubuntu 20.04, I am still unable to reproduce.

**Comment by aneesahmedpro** [comment] 2020-05-05 18:41
> In line with the suggestion from @bobismijnnaam I have now now made commit [ff6a6ad](https://github.com/Syncplay/syncplay/commit/ff6a6ad5a50180838fbd84c8f110d0b11495ff87) which deletes the line `playerController.SLAVE_ARGS.append('--data-path={}'.format(playerController.vlcDataPath))` from `VLC.py` which I think was redundant in any case. Can someone please try the GIT HEAD version of Syncplay and let me know if it fixes VLC on Ubuntu.

I just downloaded the snap with `snap download syncplay`, unpacked it, removed the line according to commit [ff6a6ad](https://github.com/Syncplay/v1.6.4syncplay/commit/ff6a6ad5a50180838fbd84c8f110d0b11495ff87), packed into a new snap, and installed it. Still didn't work. My VLC (v3.0.8) is from `apt`.

**Comment by aneesahmedpro** [comment] 2020-05-05 20:31
> > In line with the suggestion from @bobismijnnaam I have now now made commit [ff6a6ad](https://github.com/Syncplay/syncplay/commit/ff6a6ad5a50180838fbd84c8f110d0b11495ff87) which deletes the line `playerController.SLAVE_ARGS.append('--data-path={}'.format(playerController.vlcDataPath))` from `VLC.py` which I think was redundant in any case. Can someone please try the GIT HEAD version of Syncplay and let me know if it fixes VLC on Ubuntu.
> 
> I just downloaded the snap with `snap download syncplay`, unpacked it, removed the line according to commit [ff6a6ad](https://github.com/Syncplay/v1.6.4syncplay/commit/ff6a6ad5a50180838fbd84c8f110d0b11495ff87), packed into a new snap, and installed it. Still didn't work. My VLC (v3.0.8) is from `apt`.

I just downloaded the source code corresponding to the commit [ff6a6ad](https://github.com/Syncplay/v1.6.4syncplay/commit/ff6a6ad5a50180838fbd84c8f110d0b11495ff87), and compiled the project. It works. (Ubuntu 18.04.4). Yay :smile: 

Does this mean the problem lies in the `snap` technology? (I wouldn't be surprised :expressionless:)

**Comment by Et0h** [comment] 2020-09-18 18:10
AFAIK this is resolved in latest version so closing. Let me know if the issue recurs.

**Closed by Et0h** 2020-09-18 18:10 UTC
Labels: Linux/snap, bug / problem
