### ISSUE TITLE
Syncplay 1.5.1 and 1.5.2 Windows Binaries don't open past configuration

### ISSUE THREAD

**Issue by xNinjaKittyx** [Syncplay/syncplay#170] opened 2018-01-12 02:43 UTC
I downloaded Syncplay 1.5.2 Beta 1 and noticed it wasn't opening. Used Syncplay 1.5.1, and wasn't working either. 1.5.0 works. I used debug flag and got the following:

```
Traceback (most recent call last):
  File "syncplay\ui\GuiConfiguration.pyo", line 395, in _saveDataAndLeave
  File "syncplay\ui\GuiConfiguration.pyo", line 298, in loadLastUpdateCheckDate
AttributeError: 'unicode' object has no attribute 'toString'
```

Seems to be related to https://github.com/Syncplay/syncplay/commit/d8acdbe444bb0b41ebb5b6a49dad0c9b93036695

**Comment by alby128** [comment] 2018-01-12 09:00
That's because you experimented with Python 3 and syncplay wrote a unicode string instead of a QDatetime. The patch you linked was introduced to mitigate this PySide2 bug https://bugreports.qt.io/browse/PYSIDE-569 , but no matter what we do, jumping back and forth different PySide and Python versions will cause inconsistencies in these settings.

**Comment by xNinjaKittyx** [comment] 2018-01-12 09:18
Is this stored somewhere outside of syncplay? I'm using binaries, so it's kinda weird if there isn't an outside file to correlate with

**Comment by alby128** [comment] 2018-01-12 09:57
Yes, it is stored outside of syncplay, and it uses the same location for all the syncplay versions/binaries executed in the system. You can tell that because previous settings are loaded in your UI even if you just download a brand new binary from the website. 

According to this [documentation link](http://doc.qt.io/archives/qt-4.7/qsettings.html#platform-specific-notes), on Windows these data are stored in the register:

"On Windows, NativeFormat settings are stored in the following registry paths:
HKEY_CURRENT_USER\Software\MySoft\Star Runner
HKEY_CURRENT_USER\Software\MySoft
HKEY_LOCAL_MACHINE\Software\MySoft\Star Runner
HKEY_LOCAL_MACHINE\Software\MySoft

Note: On Windows, for 32-bit programs running in WOW64 mode, settings are stored in the following registry path: HKEY_LOCAL_MACHINE\Software\WOW6432node."

**Comment by Et0h** [comment] 2018-01-13 14:47
Hopefully 79c34f8 will resolve the issue. There is no great problem with it checking twice in the event of changing versions, although it is not ideal.

**Comment by Et0h** [comment] 2018-03-03 11:48
This issue should now be resolved by the [Syncplay 1.5.2 Official Release](http://syncplay.pl/syncplay-1-5-2/) so I'll close the issue for now. If the problem persists then please let me know.

**Comment by xNinjaKittyx** [comment] 2018-03-23 06:45
Hi, I'm still getting this issue. I went into my Registry and went to HKEY_CURRENT_USER\Software\Syncplay\Interface\Update and deleted the lastCheckedQt registry, and now it works.

**Comment by Daktyl198** [comment] 2018-04-01 04:26
A fresh install of 1.5.2 worked fine for me (other than having issues connecting to your update servers). My guess is that xNinjaKittyx was experience a registry problem from a previous beta version after updating?

**Comment by xNinjaKittyx** [comment] 2018-04-01 06:35
like albertosottile already mentioned, it's a registry problem when someone installs Qt to compile their own syncplay using python3

 This isn't going to apply to everyone. The fix is to either delete lastCheckedQt registry, or reset the lastCheckedQt registry when SyncPlay can't understand it. (which was what Et0h was trying to do I believe?). I guess ticket was reopened to either revert that change, or to make sure that lastCheckedQt resets when it's a faulty registry.

**Comment by Et0h** [comment] 2018-04-01 07:50
Yes I want it to not break in that edge case.

**Comment by Et0h** [comment] 2018-04-26 20:02
xNinjaKittyx has already confirmed that deleting the registry entry fixed the issue. My commit hopefully squashes the bug altogether, but even if not it is still a corner case that shouldn't recur in the future. As such, I'll be closing this issue but if the problem does occur for anyone then let me know.

**Closed by Et0h** 2018-04-26 20:02 UTC
