### ISSUE TITLE
Windows 11: Syncplay can launch setting window but can not load its main window

### ISSUE THREAD

**Issue by ShiroNek0** [Syncplay/syncplay#520] opened 2022-04-04 12:12 UTC
**Describe the bug**
Recently I can not load Syncplay main window (the window that has playlist).
I still can open the configuration window, but after hitting "Run Syncplay", only the player is opened.
Syncplay functionalities for player (play, pause...) seem to be fine, but I can't edit the playlist and have to ask my friend to do that.
Not sure what is triggering this issue, last week I decided to uninstall some unnecessary apps then this just happened.
I tried to reinstall "Visual C++ 2015-2019 Redistributable Package", but it is not working.

**To Reproduce**
Open Syncplay, then clicking on "Run Syncplay".

**Expected behavior**
Main window should appear.

**Version and platform:**
 - OS: Windows 11
 - Syncplay version and build type: 1.6.9 portable, 1.6.7 installer version

**Comment by Et0h** [comment] 2022-04-06 17:27
I've tried Syncplay 1.6.9 with Windows 11 64-bit on an Oracle VM virtual machine and it worked fine for both the dialogue and the software using mpv 0.34.0 and VLC 3.0.16 32-bit.

Could you please test the portable Syncplay 1.7.0 development build from from https://github.com/Syncplay/syncplay/actions/runs/1934118179 with the --debug command line switch on multiple media players. If you have any problems please check %APPDATA%\.syncplay.log and tell me what it says in the log. Also please let me know the version of Windows 11 are using and the media player and version.

**Comment by ShiroNek0** [comment] 2022-04-06 21:31
Sorry, I downloaded the wrong version (installer ver), after installing it the error is fixed, so no error log for this one.
I tried to uninstall it and re-install 1.6.9 and 1.6.7 again, doesn't see this error anymore.

My windows version is 21H2 build 22000.556, players are mpv 0.34.1 and MPC-HC 1.9.16.63

**Comment by Et0h** [comment] 2022-04-06 23:46
Do you intermittently have a second monitor? The issue might have been caused by https://github.com/Syncplay/syncplay/issues/504 which is fixed by running Syncplay 1.7.0 once to set the window position to something which doesn't break.

**Comment by ShiroNek0** [comment] 2022-04-07 11:51
I have a second monitor. Tried to reproduce the bug by following the steps in #504, and I can see the initial error now. I think it is the same bug with #504

**Comment by Et0h** [comment] 2022-04-07 12:03
Thanks for testing this @ShiroNek0. Given that #504 is fixed in Syncplay 1.7.0 I'll close this issue.

**Closed by Et0h** 2022-04-07 12:03 UTC
Labels: bug / problem
