### ISSUE TITLE
Videos fails to play on 1.7.0-beta1

### ISSUE THREAD

**Issue by ExTBH** [Syncplay/syncplay#555] opened 2022-10-12 17:56 UTC
**Describe the bug**
Videos failed to start and VLC reports codec errors
Below are .mkv files
```
Codec not supported:
VLC could not decode the format "hevc" (MPEG-H Part2/HEVC (H.265))
Codec not supported:
VLC could not decode the format "eac3" (A/52 B Audio (aka E-AC3))
```
Different media shows different output
Another file
```
Codec not supported:
VLC could not decode the format "h264" (H264 - MPEG-4 AVC (part 10))
Codec not supported:
VLC could not decode the format "eac3" (A/52 B Audio (aka E-AC3))
```
I've tested 1 mp4 file, it played audio without video
```
Codec not supported:
VLC could not decode the format "h264" (H264 - MPEG-4 AVC (part 10))
```
**To Reproduce**
1. Start Syncplay and click run
2. Load Media by dragging or from menu
3. Error pops up

**Expected behavior**
Files run as normal

**Screenshots**

**Version and platform:**
 - OS: Arcolinux(Arch) Rolling
 - Syncplay version and build type: 1.7.0-beta1 AppImage
 - Media player and version:  VLC 3.0.17.4 

**Additional context**
The errors does not happen on version 1.6.9 it plays as normal and function well

**Comment by daniel-123** [comment] 2022-10-18 19:08
Sorry for possibly stupid question, but it's something I'd like 100% confirmed - the videos you are testing with play just fine if you use VLC directly without Syncplay?

**Comment by ExTBH** [comment] 2022-10-18 19:23
yes all works fine without SyncPlay(1.7.0-beta)

**Comment by jpopesculian** [comment] 2022-10-27 22:27
I have the same issue with the beta with the same error with an mkv file. It also seems to open up a different file picker than when selecting with VLC without Syncplay

**Comment by Et0h** [comment] 2022-10-27 22:41
It would be really helpful if you could tell us which OS you are using on which commit it stops working.

**Comment by jpopesculian** [comment] 2022-10-28 10:41
hi @Et0h haha woops, sorry, yeah very uninformative, but it was late last night. I didn't build anything from source, just downloaded from the website, but if you'd like, I can also take the latest from master and give it a go...

OS: Ubuntu 22.04.1
Working Version: Syncplay-1.6.9-x86_64.AppImage
Non-Working Version: Syncplay-1.7.0-Beta1-x86_64.AppImage
VLC version: VLC media player 3.0.16 Vetinari (revision 3.0.13-8-g41878ff4f2)

With version 1.6.9:

![Screenshot from 2022-10-28 12-37-32](https://user-images.githubusercontent.com/3604901/198568507-f5afcddc-f437-42a2-b93d-8e1d566c17f1.png)

With version 1.7.0:

![Screenshot from 2022-10-28 12-38-45](https://user-images.githubusercontent.com/3604901/198568618-32342145-72c0-42c9-9264-ecc159e09d08.png)

![Screenshot from 2022-10-28 12-38-53](https://user-images.githubusercontent.com/3604901/198568562-4736a251-68fe-4bd2-8788-88b55932222a.png)

**Comment by albertosottile** [comment] 2022-10-28 12:21
@jpopesculian Can you try again with the latest AppImage build from the CI, available here https://github.com/Syncplay/syncplay/actions/runs/3315737387 ? Thanks

**Comment by Et0h** [comment] 2022-11-05 19:32
> @jpopesculian Can you try again with the latest AppImage build from the CI, available here https://github.com/Syncplay/syncplay/actions/runs/3315737387 ? Thanks

@ExTBH: It'd also be great if you could also test what Alberto posted to see if it fixes the issue.

**Comment by ExTBH** [comment] 2022-11-07 20:55
forgot about it, exam week too busy, it looks the same.
```
Codec not supported:
VLC could not decode the format "hevc" (MPEG-H Part2/HEVC (H.265))
Codec not supported:
VLC could not decode the format "eac3" (A/52 B Audio (aka E-AC3))

```

**Comment by jpopesculian** [comment] 2022-11-11 22:53
Same here :( no change with the downloaded AppImage

**Comment by Et0h** [comment] 2022-11-12 16:50
@jpopesculian & @ExTBH It'd be helpful if we could track down which commit caused the issue. The oldest commit with a non-expired AppImage is https://github.com/Syncplay/syncplay/suites/8453162032/artifacts/375010389 from 24th September 2022. Does VLC work in that commit or not? If it works then you can look at the AppImages in the artefacts of more recent commits to help us figure out when things broke. If it doesn't work it tells us the commit was older than 24th Stepmber.

**Comment by ExTBH** [comment] 2022-11-12 17:01
this also doesnt work

**Comment by Et0h** [comment] 2022-11-12 21:23
Thanks for testing. Does 1.7.0 Snapshot 1 from 28th October 2021 work? https://github.com/Syncplay/syncplay/releases/tag/v1.7.0-snapshot1

**Comment by ExTBH** [comment] 2022-11-13 08:16
Both of these works

**Comment by Et0h** [comment] 2022-11-27 21:52
That helps narrow it down, but I'm still not sure which commit is causing the problem. If anyone wants to help us track down the issue then please build the AppImage using different commits from 7th November onwards using an Ubuntu VM until it breaks and then let us know which commit is breaking it.

**Comment by ExTBH** [comment] 2022-12-05 07:27
I was trying to build an app image on a VM but i got stuck there's no build instructions so i was doing similar steps to the app image action, then i remembered i had the source code set up in my Host, i opened it and pulled latest stuff and it works!
Running from source: V1.7.0 beta 1 release 102
VLC: 3.0.18 Vetinari
i don't remember testing from source before, the problem looks like not from SyncPlay but from packaging it?

**Comment by daniel-123** [comment] 2022-12-07 17:52
@ExTBH can you try an AppImage built in newer environment? There is a few in result of [this action](https://github.com/Syncplay/syncplay/actions/runs/3641430192). I'm particularly hopeful that the one built on Ubuntu 20.04 will work, but the 22.04 might also be a second option worth checking.

**Comment by ExTBH** [comment] 2022-12-07 19:16
Both built with 20.04 and 22.04 seg faults
```
Program received signal SIGSEGV, Segmentation fault.
0x00007ffff5e0eecb in SbkObject_TypeF () from /tmp/.mount_SyncplKkQZKR/usr/conda/lib/python3.9/site-packages/shiboken2/libshiboken2.abi3.so.5.15
```

**Comment by Et0h** [comment] 2022-12-22 13:54
Can you please try the latest build of Syncplay-1.7.0-ubuntu-18.04-x86_64.AppImage at https://github.com/Syncplay/syncplay/suites/9912347462/artifacts/479228859 and let me know if it fixes your VLC issues?

**Comment by ExTBH** [comment] 2022-12-28 08:10
@Et0h same
```
Codec not supported:
VLC could not decode the format "hevc" (MPEG-H Part2/HEVC (H.265))
Codec not supported:
VLC could not decode the format "trhd" (TrueHD Audio)
Codec not supported:
VLC could not decode the format "a52 " (A52 Audio (aka AC3))

```

**Comment by Et0h** [comment] 2022-12-29 21:55
I just tested that build with Arcolinux on a VM and can confirm the error. I also got errors while trying to to run it with mpv.

This means that until you (or someone else) goes through each commit to figure out which one is causing the problem then Syncplay 1.7.0 doesn't appear to support Arcolinux. Fortunately Syncplay 1.6.9 and 1.7.0 beta 1 are perfectly adequate options for now. In the future the problem might end up getting resolved if we move to a newer base version of Linux in the future.

**Comment by ExTBH** [comment] 2022-12-30 17:49
i do not know how SyncPlay builds app images, but if its a dependency maybe build one of the working versions now and if the dependency if the problem it should error, if its cloned to this repository we could check the history of it and see whats new

**Comment by Et0h** [comment] 2023-04-08 16:27
Does this issue also persistent with Syncplay 1.7.0?

**Comment by ExTBH** [comment] 2023-04-08 19:23
im not on arco anymore but on Manjaro now, there seem to be an SSL error?

cert is for https://syncplay.pl without https://*syncplay.pl

![image](https://user-images.githubusercontent.com/84900328/230739162-343107e1-d1a7-4ebb-b8ac-805e15a2e3dc.png)

![image](https://user-images.githubusercontent.com/84900328/230739202-5882b493-149a-417a-aa61-82b73cd3b8e9.png)

**Comment by Et0h** [comment] 2023-04-08 20:26
> im not on arco anymore but on Manjaro now, there seem to be an SSL error?
> 

Please use https://syncplay.pl without the www.

**Comment by ExTBH** [comment] 2023-04-08 20:31
still errors when checking for update videos work fine in Manjaro i dont get the original errors

![image](https://user-images.githubusercontent.com/84900328/230741362-4e7f3d46-c41f-46ac-887e-51d310750a5c.png)

**Comment by Et0h** [comment] 2023-04-14 20:01
I've got the same error from the AppImage on Ubuntu 22.0.4.1 LTS which I ran on Windows 10 via Oracle VM VirtualBox.

One way to fix it might be to use code like `certContext= ssl.create_default_context(cafile=certifi.where())` in `client.py` and `utils.py` and then change the references in `urllib.request.urlopen` in those files to include the paramater `context=certContext`.

However, I'd need to code it carefully as that might cause problems on macOS and possibly some other setups, so it'd need to have some fallback (maybe something like `certContext =  ssl._create_unverified_context()`).

**Comment by Et0h** [comment] 2023-11-09 19:24
I am closing this issue because Syncplay has now discontinued AppImage support. See: https://github.com/Syncplay/syncplay/issues/643 for more details. If an issue recurs with the Deb package or Tarball then please re-open this comment and let us know of the details.

**Closed as completed by Et0h** 2023-11-09 19:24 UTC
Labels: bug / problem, Linux/AppImage
