### ISSUE TITLE
mpv on screen chat broken when using own server (race condition)

### ISSUE THREAD

**Issue by Abu-AM** [Syncplay/syncplay#545] opened 2022-07-16 19:42 UTC
Tried it with the latest beta release and the current 1.6.9 release using the latest mpv with no extra configs. Hitting Enter in mpv won't bring up the chat. I reverted to an old version for both syncplay and mpv and got it to work so I assume it's a bug with the latest releases.

**Comment by Et0h** [comment] 2022-07-17 13:55
Hi, I've just tried the latest build of Syncplay 1.7.0  on Windows 10 with mpv-x86_64-20220717-git-70fa950 which is the latest build from https://sourceforge.net/projects/mpv-player-windows/files/64bit/ and it works fine. Not sure why it isn't working for you - maybe a lua issue? Is the issue just about pressing enter not being detected, or are the formatted notifications also not showing up?

**Comment by Abu-AM** [comment] 2022-07-17 17:03
I found that it works when using public servers but when I host my own server (without TLS support) it doesn't work.

**Comment by Et0h** [comment] 2022-07-18 18:41
Okay I just looked into it, and it looks like the issue isn't with the version of Syncplay/mpv or if it is a private/public server but whether or not you are connecting to yourself. It appears that if you are connecting to yourself then the Syncplay client connects to the server so fast that some things seem to be done in the wrong order which causes the problem. I'm not sure exactly which bit happens too soon or how best to fix it, but at least I can confirm the general scope of the issue.

**Comment by Ziyann** [comment] 2023-02-15 18:43
I also encountered this issue. Connecting to a server on my local network resulted in the chat input not working in mpv (pressing enter didn't bring it up). Hosting on a close remote server also didn't work (maybe the ping was too low - around 20). My quick workaround was switching my PC to a mobile a hotspot, connecting to the server (so that mpv loaded properly, with working chat - maybe because of the higher ping), then switching back my PC to the wired network.

**Comment by Et0h** [comment] 2023-02-19 17:42
The issue should be fixed by e1bcf12, meaning you should now be able to use the chat feature when connecting to localhost without having to use mobile hotspots, etc.

@Ziyann and @Abu-AM Could you please test this and confirm that it fixed the bug: https://github.com/Syncplay/syncplay/actions/runs/4217399884

**Comment by Ziyann** [comment] 2023-02-19 19:35
Thanks @Et0h, I can confirm that it fixed the issue for me - chat input works fine when connecting to localhost now.

**Comment by Et0h** [comment] 2023-02-19 22:16
Great. In that case I'll consider this matter closed.

**Closed by Et0h** 2023-02-19 22:16 UTC
Labels: bug / problem
