### ISSUE TITLE
[OS X] Can't add files to shared playlist.

### ISSUE THREAD

**Issue by Duamer** [Syncplay/syncplay#146] opened 2017-09-15 04:02 UTC
This problem occurred in two different systems I have. A clean slate system that only had Syncplay installed and my main, lived-in system.

I can'd add files to the shared playlist. Neither drag-and-drop, nor right-click, "Add file(s) to bottom of playlist" function. I momentarily see a files browser window pop up when I right-click.
I can add URLs to the playlist and they work as they should. I've setup the media directories and had a different user make the playlist and that works as well.

**Comment by alby128** [comment] 2017-09-15 13:07
Confirmed. Looking for a workaround. Thanks.

**Comment by alby128** [comment] 2017-09-15 14:22
If you have time, please test the workaround that I have just pushed to my branch: https://github.com/alby128/syncplay . Right now, I tested it on 10.12.6 and it works for me.

**Comment by Duamer** [comment] 2017-09-15 23:31
How do I install pyobjc with homebrew? I used the homebrew method of your directions.

Incase that's not what's causing my error, here's what I got:

users-iMac:syncplay user$ python2 syncplayClient.py
2017-09-15 19:22:39.429 Python[628:5526] modalSession has been exited prematurely - check for a reentrant call to endModalSession:
Traceback (most recent call last):
  File "syncplayClient.py", line 19, in <module>
    SyncplayClientManager().run()
  File "/Users/user/syncplay/syncplay/clientManager.py", line 9, in run
    interface = ui.getUi(graphical=not config["noGui"])
  File "/Users/user/syncplay/syncplay/ui/__init__.py", line 9, in getUi
    ui = GraphicalUI()
NameError: global name 'GraphicalUI' is not defined
Segmentation fault: 11

**Comment by alby128** [comment] 2017-09-15 23:39
To install pyobjc on your homebrew, just run `pip2 install pyobjc`. However, I have to admit that your error message puzzles me a little... Where and how did you get it? When you tried to add something to a shared playlist?

**Comment by Duamer** [comment] 2017-09-16 04:43
Looks like that fixed it. I'll be able to test it by Monday to see if it works with other users in the room.

I got that error when I clicked "Store configuration and run Syncplay."

**Comment by alby128** [comment] 2017-09-18 21:26
@Duamer Did you test this fix with other users?

**Comment by Duamer** [comment] 2017-09-18 23:33
Testing now and it looks good. I was able to setup the room and the order user joined. Works like it does when I was using the windows client.

**Comment by Duamer** [comment] 2017-09-18 23:33
Testing now and it looks good. I was able to setup the room and the order
user joined. Works like it does when I was using the windows client.

**Comment by alby128** [comment] 2017-09-19 06:52
@Duamer Thanks, but please reopen this, as it has only been fixed in my fork. To fix it here, we still need to merge the PR #148 .

**Closed** 2017-10-01 19:55 UTC
Labels: bug, OS X
